# Generated by Django 5.2.1 on 2025-08-11 04:00

import django.core.validators
import model_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the model', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('file', models.FileField(help_text='GLB or GLTF model file', upload_to=model_files.models.model_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf'])])),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '3D Model',
                'verbose_name_plural': '3D Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_rotate', models.BooleanField(default=False)),
                ('background_color', models.CharField(default='#1a1a1a', max_length=7)),
                ('wireframe_mode', models.BooleanField(default=False)),
                ('camera_position_x', models.FloatField(default=0)),
                ('camera_position_y', models.FloatField(default=0)),
                ('camera_position_z', models.FloatField(default=5)),
                ('ambient_light_intensity', models.FloatField(default=0.6)),
                ('directional_light_intensity', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
