# Generated by Django 5.2.1 on 2025-06-01 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('customer_limit', models.IntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_customer', to='accounts.customer')),
                ('selected_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_tenders', to='accounts.contractor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_service', to='needs.services')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_supervisor', to='accounts.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='TenderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.contractor')),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='works.tenders')),
            ],
        ),
        migrations.CreateModel(
            name='Tender_requirments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=15)),
                ('requirments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_tenders', to='needs.requirments')),
                ('tenders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_requirements', to='works.tenders')),
            ],
            options={
                'unique_together': {('tenders', 'requirments')},
            },
        ),
        migrations.CreateModel(
            name='TenderBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='accounts.contractor')),
                ('tender_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='works.tender_requirments')),
            ],
            options={
                'unique_together': {('tender_requirement', 'contractor')},
            },
        ),
        migrations.CreateModel(
            name='Tender_contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_tenders', to='accounts.contractor')),
                ('tenders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_contractors', to='works.tenders')),
            ],
            options={
                'unique_together': {('tenders', 'tender_contractor')},
            },
        ),
    ]
